from vector_db.PineConeDB import retriever
from .LLM import final_response


def query(user_query):

    """
    Query the retriever model with the given user query, and return the answer
    based on the results of the query.

    The answer is generated using the final_response function, which generates
    a markdown response using the Gemini model.

    :param user_query: The user query to be queried to the retriever model
    :return: A markdown response generated by the Gemini model
    """
    results = retriever.invoke(user_query)

    PROMPT_TEMPLATE = f"""
    Answer the question based only on the following context:

    {results}

    ---

    Answer the question based on the above context: {user_query}

    Don't answer anything out of context
    """
    
    for result in results:
        print(result)
        print()

    return final_response(PROMPT_TEMPLATE)
